version: '3'

services:
  backend:
    build: 
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  web:
    build:
      context: ./client/next-web/
      args:
        NEXT_PUBLIC_FIREBASE_API_KEY: AIzaSyAVqhwbdB8I56HAMVVlgJKZcfrBkKI2AhQ
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: assistly-kubernetes.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: assistly-kubernetes
        NEXT_PUBLIC_FIREBASE_APP_ID: 1:806733379891:web:48bf124c0d9b90298e6646
        REACT_APP_BUILD_NUMBER: 0.0.1
        NEXT_PUBLIC_API_HOST: http://127.0.0.1:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAVqhwbdB8I56HAMVVlgJKZcfrBkKI2AhQ
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=assistly-kubernetes.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=assistly-kubernetes
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=assistly-kubernetes.appspot.com
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=806733379891
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:806733379891:web:48bf124c0d9b90298e6646
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XVWF8XDKS5
      - REACT_APP_BUILD_NUMBER=0.0.1
      - NEXT_PUBLIC_API_HOST=http://backend:8000
      - API_HOST=http://backend:8000

networks:
  default:
    driver: bridge
