version: '3'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: temo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password1!
    healthcheck:
      test: "pg_isready --dbname temo --username=admin"
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  web:
    build: ./client/web/
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./.env
