const edgeTTSVoiceIds = [
  {
    voice_id: 'af-ZA-AdriNeural',
    name: 'Adri',
    lang: 'Afrikaans',
    from: 'ZA',
    gender: 'Female',
  },
  {
    voice_id: 'af-ZA-WillemNeural',
    name: 'Willem',
    lang: 'Afrikaans',
    from: 'ZA',
    gender: 'Male',
  },
  {
    voice_id: 'am-ET-AmehaNeural',
    name: 'Ameha',
    lang: 'Amharic',
    from: 'ET',
    gender: 'Male',
  },
  {
    voice_id: 'am-ET-MekdesNeural',
    name: 'Mekdes',
    lang: 'Amharic',
    from: 'ET',
    gender: 'Female',
  },
  {
    voice_id: 'ar-AE-FatimaNeural',
    name: 'Fatima',
    lang: 'Arabic',
    from: 'AE',
    gender: 'Female',
  },
  {
    voice_id: 'ar-AE-HamdanNeural',
    name: 'Hamdan',
    lang: 'Arabic',
    from: 'AE',
    gender: 'Male',
  },
  {
    voice_id: 'ar-BH-AliNeural',
    name: 'Ali',
    lang: 'Arabic',
    from: 'BH',
    gender: 'Male',
  },
  {
    voice_id: 'ar-BH-LailaNeural',
    name: 'Laila',
    lang: 'Arabic',
    from: 'BH',
    gender: 'Female',
  },
  {
    voice_id: 'ar-DZ-AminaNeural',
    name: 'Amina',
    lang: 'Arabic',
    from: 'DZ',
    gender: 'Female',
  },
  {
    voice_id: 'ar-DZ-IsmaelNeural',
    name: 'Ismael',
    lang: 'Arabic',
    from: 'DZ',
    gender: 'Male',
  },
  {
    voice_id: 'ar-EG-SalmaNeural',
    name: 'Salma',
    lang: 'Arabic',
    from: 'EG',
    gender: 'Female',
  },
  {
    voice_id: 'ar-EG-ShakirNeural',
    name: 'Shakir',
    lang: 'Arabic',
    from: 'EG',
    gender: 'Male',
  },
  {
    voice_id: 'ar-IQ-BasselNeural',
    name: 'Bassel',
    lang: 'Arabic',
    from: 'IQ',
    gender: 'Male',
  },
  {
    voice_id: 'ar-IQ-RanaNeural',
    name: 'Rana',
    lang: 'Arabic',
    from: 'IQ',
    gender: 'Female',
  },
  {
    voice_id: 'ar-JO-SanaNeural',
    name: 'Sana',
    lang: 'Arabic',
    from: 'JO',
    gender: 'Female',
  },
  {
    voice_id: 'ar-JO-TaimNeural',
    name: 'Taim',
    lang: 'Arabic',
    from: 'JO',
    gender: 'Male',
  },
  {
    voice_id: 'ar-KW-FahedNeural',
    name: 'Fahed',
    lang: 'Arabic',
    from: 'KW',
    gender: 'Male',
  },
  {
    voice_id: 'ar-KW-NouraNeural',
    name: 'Noura',
    lang: 'Arabic',
    from: 'KW',
    gender: 'Female',
  },
  {
    voice_id: 'ar-LB-LaylaNeural',
    name: 'Layla',
    lang: 'Arabic',
    from: 'LB',
    gender: 'Female',
  },
  {
    voice_id: 'ar-LB-RamiNeural',
    name: 'Rami',
    lang: 'Arabic',
    from: 'LB',
    gender: 'Male',
  },
  {
    voice_id: 'ar-LY-ImanNeural',
    name: 'Iman',
    lang: 'Arabic',
    from: 'LY',
    gender: 'Female',
  },
  {
    voice_id: 'ar-LY-OmarNeural',
    name: 'Omar',
    lang: 'Arabic',
    from: 'LY',
    gender: 'Male',
  },
  {
    voice_id: 'ar-MA-JamalNeural',
    name: 'Jamal',
    lang: 'Arabic',
    from: 'MA',
    gender: 'Male',
  },
  {
    voice_id: 'ar-MA-MounaNeural',
    name: 'Mouna',
    lang: 'Arabic',
    from: 'MA',
    gender: 'Female',
  },
  {
    voice_id: 'ar-OM-AbdullahNeural',
    name: 'Abdullah',
    lang: 'Arabic',
    from: 'OM',
    gender: 'Male',
  },
  {
    voice_id: 'ar-OM-AyshaNeural',
    name: 'Aysha',
    lang: 'Arabic',
    from: 'OM',
    gender: 'Female',
  },
  {
    voice_id: 'ar-QA-AmalNeural',
    name: 'Amal',
    lang: 'Arabic',
    from: 'QA',
    gender: 'Female',
  },
  {
    voice_id: 'ar-QA-MoazNeural',
    name: 'Moaz',
    lang: 'Arabic',
    from: 'QA',
    gender: 'Male',
  },
  {
    voice_id: 'ar-SA-HamedNeural',
    name: 'Hamed',
    lang: 'Arabic',
    from: 'SA',
    gender: 'Male',
  },
  {
    voice_id: 'ar-SA-ZariyahNeural',
    name: 'Zariyah',
    lang: 'Arabic',
    from: 'SA',
    gender: 'Female',
  },
  {
    voice_id: 'ar-SY-AmanyNeural',
    name: 'Amany',
    lang: 'Arabic',
    from: 'SY',
    gender: 'Female',
  },
  {
    voice_id: 'ar-SY-LaithNeural',
    name: 'Laith',
    lang: 'Arabic',
    from: 'SY',
    gender: 'Male',
  },
  {
    voice_id: 'ar-TN-HediNeural',
    name: 'Hedi',
    lang: 'Arabic',
    from: 'TN',
    gender: 'Male',
  },
  {
    voice_id: 'ar-TN-ReemNeural',
    name: 'Reem',
    lang: 'Arabic',
    from: 'TN',
    gender: 'Female',
  },
  {
    voice_id: 'ar-YE-MaryamNeural',
    name: 'Maryam',
    lang: 'Arabic',
    from: 'YE',
    gender: 'Female',
  },
  {
    voice_id: 'ar-YE-SalehNeural',
    name: 'Saleh',
    lang: 'Arabic',
    from: 'YE',
    gender: 'Male',
  },
  {
    voice_id: 'az-AZ-BabekNeural',
    name: 'Babek',
    lang: 'Azerbaijani',
    from: 'AZ',
    gender: 'Male',
  },
  {
    voice_id: 'az-AZ-BanuNeural',
    name: 'Banu',
    lang: 'Azerbaijani',
    from: 'AZ',
    gender: 'Female',
  },
  {
    voice_id: 'bg-BG-BorislavNeural',
    name: 'Borislav',
    lang: 'Bulgarian',
    from: 'BG',
    gender: 'Male',
  },
  {
    voice_id: 'bg-BG-KalinaNeural',
    name: 'Kalina',
    lang: 'Bulgarian',
    from: 'BG',
    gender: 'Female',
  },
  {
    voice_id: 'bn-BD-NabanitaNeural',
    name: 'Nabanita',
    lang: 'Bengali',
    from: 'BD',
    gender: 'Female',
  },
  {
    voice_id: 'bn-BD-PradeepNeural',
    name: 'Pradeep',
    lang: 'Bengali',
    from: 'BD',
    gender: 'Male',
  },
  {
    voice_id: 'bn-IN-BashkarNeural',
    name: 'Bashkar',
    lang: 'Bengali',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'bn-IN-TanishaaNeural',
    name: 'Tanishaa',
    lang: 'Bengali',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'bs-BA-GoranNeural',
    name: 'Goran',
    lang: 'Bosnian',
    from: 'BA',
    gender: 'Male',
  },
  {
    voice_id: 'bs-BA-VesnaNeural',
    name: 'Vesna',
    lang: 'Bosnian',
    from: 'BA',
    gender: 'Female',
  },
  {
    voice_id: 'ca-ES-EnricNeural',
    name: 'Enric',
    lang: 'Catalan',
    from: 'ES',
    gender: 'Male',
  },
  {
    voice_id: 'ca-ES-JoanaNeural',
    name: 'Joana',
    lang: 'Catalan',
    from: 'ES',
    gender: 'Female',
  },
  {
    voice_id: 'cs-CZ-AntoninNeural',
    name: 'Antonin',
    lang: 'Czech',
    from: 'CZ',
    gender: 'Male',
  },
  {
    voice_id: 'cs-CZ-VlastaNeural',
    name: 'Vlasta',
    lang: 'Czech',
    from: 'CZ',
    gender: 'Female',
  },
  {
    voice_id: 'cy-GB-AledNeural',
    name: 'Aled',
    lang: 'Welsh',
    from: 'GB',
    gender: 'Male',
  },
  {
    voice_id: 'cy-GB-NiaNeural',
    name: 'Nia',
    lang: 'Welsh',
    from: 'GB',
    gender: 'Female',
  },
  {
    voice_id: 'da-DK-ChristelNeural',
    name: 'Christel',
    lang: 'Danish',
    from: 'DK',
    gender: 'Female',
  },
  {
    voice_id: 'da-DK-JeppeNeural',
    name: 'Jeppe',
    lang: 'Danish',
    from: 'DK',
    gender: 'Male',
  },
  {
    voice_id: 'de-AT-IngridNeural',
    name: 'Ingrid',
    lang: 'German',
    from: 'AT',
    gender: 'Female',
  },
  {
    voice_id: 'de-AT-JonasNeural',
    name: 'Jonas',
    lang: 'German',
    from: 'AT',
    gender: 'Male',
  },
  {
    voice_id: 'de-CH-JanNeural',
    name: 'Jan',
    lang: 'German',
    from: 'CH',
    gender: 'Male',
  },
  {
    voice_id: 'de-CH-LeniNeural',
    name: 'Leni',
    lang: 'German',
    from: 'CH',
    gender: 'Female',
  },
  {
    voice_id: 'de-DE-AmalaNeural',
    name: 'Amala',
    lang: 'German',
    from: 'DE',
    gender: 'Female',
  },
  {
    voice_id: 'de-DE-ConradNeural',
    name: 'Conrad',
    lang: 'German',
    from: 'DE',
    gender: 'Male',
  },
  {
    voice_id: 'de-DE-KatjaNeural',
    name: 'Katja',
    lang: 'German',
    from: 'DE',
    gender: 'Female',
  },
  {
    voice_id: 'de-DE-KillianNeural',
    name: 'Killian',
    lang: 'German',
    from: 'DE',
    gender: 'Male',
  },
  {
    voice_id: 'el-GR-AthinaNeural',
    name: 'Athina',
    lang: 'Greek',
    from: 'GR',
    gender: 'Female',
  },
  {
    voice_id: 'el-GR-NestorasNeural',
    name: 'Nestoras',
    lang: 'Greek',
    from: 'GR',
    gender: 'Male',
  },
  {
    voice_id: 'en-AU-NatashaNeural',
    name: 'Natasha',
    lang: 'English',
    from: 'AU',
    gender: 'Female',
  },
  {
    voice_id: 'en-AU-WilliamNeural',
    name: 'William',
    lang: 'English',
    from: 'AU',
    gender: 'Male',
  },
  {
    voice_id: 'en-CA-ClaraNeural',
    name: 'Clara',
    lang: 'English',
    from: 'CA',
    gender: 'Female',
  },
  {
    voice_id: 'en-CA-LiamNeural',
    name: 'Liam',
    lang: 'English',
    from: 'CA',
    gender: 'Male',
  },
  {
    voice_id: 'en-GB-LibbyNeural',
    name: 'Libby',
    lang: 'English',
    from: 'GB',
    gender: 'Female',
  },
  {
    voice_id: 'en-GB-MaisieNeural',
    name: 'Maisie',
    lang: 'English',
    from: 'GB',
    gender: 'Female',
  },
  {
    voice_id: 'en-GB-RyanNeural',
    name: 'Ryan',
    lang: 'English',
    from: 'GB',
    gender: 'Male',
  },
  {
    voice_id: 'en-GB-SoniaNeural',
    name: 'Sonia',
    lang: 'English',
    from: 'GB',
    gender: 'Female',
  },
  {
    voice_id: 'en-GB-ThomasNeural',
    name: 'Thomas',
    lang: 'English',
    from: 'GB',
    gender: 'Male',
  },
  {
    voice_id: 'en-HK-SamNeural',
    name: 'Sam',
    lang: 'English',
    from: 'HK',
    gender: 'Male',
  },
  {
    voice_id: 'en-HK-YanNeural',
    name: 'Yan',
    lang: 'English',
    from: 'HK',
    gender: 'Female',
  },
  {
    voice_id: 'en-IE-ConnorNeural',
    name: 'Connor',
    lang: 'English',
    from: 'IE',
    gender: 'Male',
  },
  {
    voice_id: 'en-IE-EmilyNeural',
    name: 'Emily',
    lang: 'English',
    from: 'IE',
    gender: 'Female',
  },
  {
    voice_id: 'en-IN-NeerjaExpressiveNeural',
    name: 'NeerjaExpressive',
    lang: 'English',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'en-IN-NeerjaNeural',
    name: 'Neerja',
    lang: 'English',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'en-IN-PrabhatNeural',
    name: 'Prabhat',
    lang: 'English',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'en-KE-AsiliaNeural',
    name: 'Asilia',
    lang: 'English',
    from: 'KE',
    gender: 'Female',
  },
  {
    voice_id: 'en-KE-ChilembaNeural',
    name: 'Chilemba',
    lang: 'English',
    from: 'KE',
    gender: 'Male',
  },
  {
    voice_id: 'en-NG-AbeoNeural',
    name: 'Abeo',
    lang: 'English',
    from: 'NG',
    gender: 'Male',
  },
  {
    voice_id: 'en-NG-EzinneNeural',
    name: 'Ezinne',
    lang: 'English',
    from: 'NG',
    gender: 'Female',
  },
  {
    voice_id: 'en-NZ-MitchellNeural',
    name: 'Mitchell',
    lang: 'English',
    from: 'NZ',
    gender: 'Male',
  },
  {
    voice_id: 'en-NZ-MollyNeural',
    name: 'Molly',
    lang: 'English',
    from: 'NZ',
    gender: 'Female',
  },
  {
    voice_id: 'en-PH-JamesNeural',
    name: 'James',
    lang: 'English',
    from: 'PH',
    gender: 'Male',
  },
  {
    voice_id: 'en-PH-RosaNeural',
    name: 'Rosa',
    lang: 'English',
    from: 'PH',
    gender: 'Female',
  },
  {
    voice_id: 'en-SG-LunaNeural',
    name: 'Luna',
    lang: 'English',
    from: 'SG',
    gender: 'Female',
  },
  {
    voice_id: 'en-SG-WayneNeural',
    name: 'Wayne',
    lang: 'English',
    from: 'SG',
    gender: 'Male',
  },
  {
    voice_id: 'en-TZ-ElimuNeural',
    name: 'Elimu',
    lang: 'English',
    from: 'TZ',
    gender: 'Male',
  },
  {
    voice_id: 'en-TZ-ImaniNeural',
    name: 'Imani',
    lang: 'English',
    from: 'TZ',
    gender: 'Female',
  },
  {
    voice_id: 'en-US-AnaNeural',
    name: 'Ana',
    lang: 'English',
    from: 'US',
    gender: 'Female',
  },
  {
    voice_id: 'en-US-AriaNeural',
    name: 'Aria',
    lang: 'English',
    from: 'US',
    gender: 'Female',
  },
  {
    voice_id: 'en-US-ChristopherNeural',
    name: 'Christopher',
    lang: 'English',
    from: 'US',
    gender: 'Male',
  },
  {
    voice_id: 'en-US-EricNeural',
    name: 'Eric',
    lang: 'English',
    from: 'US',
    gender: 'Male',
  },
  {
    voice_id: 'en-US-GuyNeural',
    name: 'Guy',
    lang: 'English',
    from: 'US',
    gender: 'Male',
  },
  {
    voice_id: 'en-US-JennyNeural',
    name: 'Jenny',
    lang: 'English',
    from: 'US',
    gender: 'Female',
  },
  {
    voice_id: 'en-US-MichelleNeural',
    name: 'Michelle',
    lang: 'English',
    from: 'US',
    gender: 'Female',
  },
  {
    voice_id: 'en-US-RogerNeural',
    name: 'Roger',
    lang: 'English',
    from: 'US',
    gender: 'Male',
  },
  {
    voice_id: 'en-US-SteffanNeural',
    name: 'Steffan',
    lang: 'English',
    from: 'US',
    gender: 'Male',
  },
  {
    voice_id: 'en-ZA-LeahNeural',
    name: 'Leah',
    lang: 'English',
    from: 'ZA',
    gender: 'Female',
  },
  {
    voice_id: 'en-ZA-LukeNeural',
    name: 'Luke',
    lang: 'English',
    from: 'ZA',
    gender: 'Male',
  },
  {
    voice_id: 'es-AR-ElenaNeural',
    name: 'Elena',
    lang: 'Spanish',
    from: 'AR',
    gender: 'Female',
  },
  {
    voice_id: 'es-AR-TomasNeural',
    name: 'Tomas',
    lang: 'Spanish',
    from: 'AR',
    gender: 'Male',
  },
  {
    voice_id: 'es-BO-MarceloNeural',
    name: 'Marcelo',
    lang: 'Spanish',
    from: 'BO',
    gender: 'Male',
  },
  {
    voice_id: 'es-BO-SofiaNeural',
    name: 'Sofia',
    lang: 'Spanish',
    from: 'BO',
    gender: 'Female',
  },
  {
    voice_id: 'es-CL-CatalinaNeural',
    name: 'Catalina',
    lang: 'Spanish',
    from: 'CL',
    gender: 'Female',
  },
  {
    voice_id: 'es-CL-LorenzoNeural',
    name: 'Lorenzo',
    lang: 'Spanish',
    from: 'CL',
    gender: 'Male',
  },
  {
    voice_id: 'es-CO-GonzaloNeural',
    name: 'Gonzalo',
    lang: 'Spanish',
    from: 'CO',
    gender: 'Male',
  },
  {
    voice_id: 'es-CO-SalomeNeural',
    name: 'Salome',
    lang: 'Spanish',
    from: 'CO',
    gender: 'Female',
  },
  {
    voice_id: 'es-CR-JuanNeural',
    name: 'Juan',
    lang: 'Spanish',
    from: 'CR',
    gender: 'Male',
  },
  {
    voice_id: 'es-CR-MariaNeural',
    name: 'Maria',
    lang: 'Spanish',
    from: 'CR',
    gender: 'Female',
  },
  {
    voice_id: 'es-CU-BelkysNeural',
    name: 'Belkys',
    lang: 'Spanish',
    from: 'CU',
    gender: 'Female',
  },
  {
    voice_id: 'es-CU-ManuelNeural',
    name: 'Manuel',
    lang: 'Spanish',
    from: 'CU',
    gender: 'Male',
  },
  {
    voice_id: 'es-DO-EmilioNeural',
    name: 'Emilio',
    lang: 'Spanish',
    from: 'DO',
    gender: 'Male',
  },
  {
    voice_id: 'es-DO-RamonaNeural',
    name: 'Ramona',
    lang: 'Spanish',
    from: 'DO',
    gender: 'Female',
  },
  {
    voice_id: 'es-EC-AndreaNeural',
    name: 'Andrea',
    lang: 'Spanish',
    from: 'EC',
    gender: 'Female',
  },
  {
    voice_id: 'es-EC-LuisNeural',
    name: 'Luis',
    lang: 'Spanish',
    from: 'EC',
    gender: 'Male',
  },
  {
    voice_id: 'es-ES-AlvaroNeural',
    name: 'Alvaro',
    lang: 'Spanish',
    from: 'ES',
    gender: 'Male',
  },
  {
    voice_id: 'es-ES-ElviraNeural',
    name: 'Elvira',
    lang: 'Spanish',
    from: 'ES',
    gender: 'Female',
  },
  {
    voice_id: 'es-GQ-JavierNeural',
    name: 'Javier',
    lang: 'Spanish',
    from: 'GQ',
    gender: 'Male',
  },
  {
    voice_id: 'es-GQ-TeresaNeural',
    name: 'Teresa',
    lang: 'Spanish',
    from: 'GQ',
    gender: 'Female',
  },
  {
    voice_id: 'es-GT-AndresNeural',
    name: 'Andres',
    lang: 'Spanish',
    from: 'GT',
    gender: 'Male',
  },
  {
    voice_id: 'es-GT-MartaNeural',
    name: 'Marta',
    lang: 'Spanish',
    from: 'GT',
    gender: 'Female',
  },
  {
    voice_id: 'es-HN-CarlosNeural',
    name: 'Carlos',
    lang: 'Spanish',
    from: 'HN',
    gender: 'Male',
  },
  {
    voice_id: 'es-HN-KarlaNeural',
    name: 'Karla',
    lang: 'Spanish',
    from: 'HN',
    gender: 'Female',
  },
  {
    voice_id: 'es-MX-DaliaNeural',
    name: 'Dalia',
    lang: 'Spanish',
    from: 'MX',
    gender: 'Female',
  },
  {
    voice_id: 'es-MX-JorgeNeural',
    name: 'Jorge',
    lang: 'Spanish',
    from: 'MX',
    gender: 'Male',
  },
  {
    voice_id: 'es-NI-FedericoNeural',
    name: 'Federico',
    lang: 'Spanish',
    from: 'NI',
    gender: 'Male',
  },
  {
    voice_id: 'es-NI-YolandaNeural',
    name: 'Yolanda',
    lang: 'Spanish',
    from: 'NI',
    gender: 'Female',
  },
  {
    voice_id: 'es-PA-MargaritaNeural',
    name: 'Margarita',
    lang: 'Spanish',
    from: 'PA',
    gender: 'Female',
  },
  {
    voice_id: 'es-PA-RobertoNeural',
    name: 'Roberto',
    lang: 'Spanish',
    from: 'PA',
    gender: 'Male',
  },
  {
    voice_id: 'es-PE-AlexNeural',
    name: 'Alex',
    lang: 'Spanish',
    from: 'PE',
    gender: 'Male',
  },
  {
    voice_id: 'es-PE-CamilaNeural',
    name: 'Camila',
    lang: 'Spanish',
    from: 'PE',
    gender: 'Female',
  },
  {
    voice_id: 'es-PR-KarinaNeural',
    name: 'Karina',
    lang: 'Spanish',
    from: 'PR',
    gender: 'Female',
  },
  {
    voice_id: 'es-PR-VictorNeural',
    name: 'Victor',
    lang: 'Spanish',
    from: 'PR',
    gender: 'Male',
  },
  {
    voice_id: 'es-PY-MarioNeural',
    name: 'Mario',
    lang: 'Spanish',
    from: 'PY',
    gender: 'Male',
  },
  {
    voice_id: 'es-PY-TaniaNeural',
    name: 'Tania',
    lang: 'Spanish',
    from: 'PY',
    gender: 'Female',
  },
  {
    voice_id: 'es-SV-LorenaNeural',
    name: 'Lorena',
    lang: 'Spanish',
    from: 'SV',
    gender: 'Female',
  },
  {
    voice_id: 'es-SV-RodrigoNeural',
    name: 'Rodrigo',
    lang: 'Spanish',
    from: 'SV',
    gender: 'Male',
  },
  {
    voice_id: 'es-US-AlonsoNeural',
    name: 'Alonso',
    lang: 'Spanish',
    from: 'US',
    gender: 'Male',
  },
  {
    voice_id: 'es-US-PalomaNeural',
    name: 'Paloma',
    lang: 'Spanish',
    from: 'US',
    gender: 'Female',
  },
  {
    voice_id: 'es-UY-MateoNeural',
    name: 'Mateo',
    lang: 'Spanish',
    from: 'UY',
    gender: 'Male',
  },
  {
    voice_id: 'es-UY-ValentinaNeural',
    name: 'Valentina',
    lang: 'Spanish',
    from: 'UY',
    gender: 'Female',
  },
  {
    voice_id: 'es-VE-PaolaNeural',
    name: 'Paola',
    lang: 'Spanish',
    from: 'VE',
    gender: 'Female',
  },
  {
    voice_id: 'es-VE-SebastianNeural',
    name: 'Sebastian',
    lang: 'Spanish',
    from: 'VE',
    gender: 'Male',
  },
  {
    voice_id: 'et-EE-AnuNeural',
    name: 'Anu',
    lang: 'Estonian',
    from: 'EE',
    gender: 'Female',
  },
  {
    voice_id: 'et-EE-KertNeural',
    name: 'Kert',
    lang: 'Estonian',
    from: 'EE',
    gender: 'Male',
  },
  {
    voice_id: 'fa-IR-DilaraNeural',
    name: 'Dilara',
    lang: 'Persian',
    from: 'IR',
    gender: 'Female',
  },
  {
    voice_id: 'fa-IR-FaridNeural',
    name: 'Farid',
    lang: 'Persian',
    from: 'IR',
    gender: 'Male',
  },
  {
    voice_id: 'fi-FI-HarriNeural',
    name: 'Harri',
    lang: 'Finnish',
    from: 'FI',
    gender: 'Male',
  },
  {
    voice_id: 'fi-FI-NooraNeural',
    name: 'Noora',
    lang: 'Finnish',
    from: 'FI',
    gender: 'Female',
  },
  {
    voice_id: 'fil-PH-AngeloNeural',
    name: 'Angelo',
    lang: 'Filipino',
    from: 'PH',
    gender: 'Male',
  },
  {
    voice_id: 'fil-PH-BlessicaNeural',
    name: 'Blessica',
    lang: 'Filipino',
    from: 'PH',
    gender: 'Female',
  },
  {
    voice_id: 'fr-BE-CharlineNeural',
    name: 'Charline',
    lang: 'French',
    from: 'BE',
    gender: 'Female',
  },
  {
    voice_id: 'fr-BE-GerardNeural',
    name: 'Gerard',
    lang: 'French',
    from: 'BE',
    gender: 'Male',
  },
  {
    voice_id: 'fr-CA-AntoineNeural',
    name: 'Antoine',
    lang: 'French',
    from: 'CA',
    gender: 'Male',
  },
  {
    voice_id: 'fr-CA-JeanNeural',
    name: 'Jean',
    lang: 'French',
    from: 'CA',
    gender: 'Male',
  },
  {
    voice_id: 'fr-CA-SylvieNeural',
    name: 'Sylvie',
    lang: 'French',
    from: 'CA',
    gender: 'Female',
  },
  {
    voice_id: 'fr-CH-ArianeNeural',
    name: 'Ariane',
    lang: 'French',
    from: 'CH',
    gender: 'Female',
  },
  {
    voice_id: 'fr-CH-FabriceNeural',
    name: 'Fabrice',
    lang: 'French',
    from: 'CH',
    gender: 'Male',
  },
  {
    voice_id: 'fr-FR-DeniseNeural',
    name: 'Denise',
    lang: 'French',
    from: 'FR',
    gender: 'Female',
  },
  {
    voice_id: 'fr-FR-EloiseNeural',
    name: 'Eloise',
    lang: 'French',
    from: 'FR',
    gender: 'Female',
  },
  {
    voice_id: 'fr-FR-HenriNeural',
    name: 'Henri',
    lang: 'French',
    from: 'FR',
    gender: 'Male',
  },
  {
    voice_id: 'ga-IE-ColmNeural',
    name: 'Colm',
    lang: 'Irish',
    from: 'IE',
    gender: 'Male',
  },
  {
    voice_id: 'ga-IE-OrlaNeural',
    name: 'Orla',
    lang: 'Irish',
    from: 'IE',
    gender: 'Female',
  },
  {
    voice_id: 'gl-ES-RoiNeural',
    name: 'Roi',
    lang: 'Galician',
    from: 'ES',
    gender: 'Male',
  },
  {
    voice_id: 'gl-ES-SabelaNeural',
    name: 'Sabela',
    lang: 'Galician',
    from: 'ES',
    gender: 'Female',
  },
  {
    voice_id: 'gu-IN-DhwaniNeural',
    name: 'Dhwani',
    lang: 'Gujarati',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'gu-IN-NiranjanNeural',
    name: 'Niranjan',
    lang: 'Gujarati',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'he-IL-AvriNeural',
    name: 'Avri',
    lang: 'Hebrew',
    from: 'IL',
    gender: 'Male',
  },
  {
    voice_id: 'he-IL-HilaNeural',
    name: 'Hila',
    lang: 'Hebrew',
    from: 'IL',
    gender: 'Female',
  },
  {
    voice_id: 'hi-IN-MadhurNeural',
    name: 'Madhur',
    lang: 'Hindi',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'hi-IN-SwaraNeural',
    name: 'Swara',
    lang: 'Hindi',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'hr-HR-GabrijelaNeural',
    name: 'Gabrijela',
    lang: 'Croatian',
    from: 'HR',
    gender: 'Female',
  },
  {
    voice_id: 'hr-HR-SreckoNeural',
    name: 'Srecko',
    lang: 'Croatian',
    from: 'HR',
    gender: 'Male',
  },
  {
    voice_id: 'hu-HU-NoemiNeural',
    name: 'Noemi',
    lang: 'Hungarian',
    from: 'HU',
    gender: 'Female',
  },
  {
    voice_id: 'hu-HU-TamasNeural',
    name: 'Tamas',
    lang: 'Hungarian',
    from: 'HU',
    gender: 'Male',
  },
  {
    voice_id: 'id-ID-ArdiNeural',
    name: 'Ardi',
    lang: 'Indonesian',
    from: 'ID',
    gender: 'Male',
  },
  {
    voice_id: 'id-ID-GadisNeural',
    name: 'Gadis',
    lang: 'Indonesian',
    from: 'ID',
    gender: 'Female',
  },
  {
    voice_id: 'is-IS-GudrunNeural',
    name: 'Gudrun',
    lang: 'Icelandic',
    from: 'IS',
    gender: 'Female',
  },
  {
    voice_id: 'is-IS-GunnarNeural',
    name: 'Gunnar',
    lang: 'Icelandic',
    from: 'IS',
    gender: 'Male',
  },
  {
    voice_id: 'it-IT-DiegoNeural',
    name: 'Diego',
    lang: 'Italian',
    from: 'IT',
    gender: 'Male',
  },
  {
    voice_id: 'it-IT-ElsaNeural',
    name: 'Elsa',
    lang: 'Italian',
    from: 'IT',
    gender: 'Female',
  },
  {
    voice_id: 'it-IT-IsabellaNeural',
    name: 'Isabella',
    lang: 'Italian',
    from: 'IT',
    gender: 'Female',
  },
  {
    voice_id: 'ja-JP-KeitaNeural',
    name: 'Keita',
    lang: 'Japanese',
    from: 'JP',
    gender: 'Male',
  },
  {
    voice_id: 'ja-JP-NanamiNeural',
    name: 'Nanami',
    lang: 'Japanese',
    from: 'JP',
    gender: 'Female',
  },
  {
    voice_id: 'jv-ID-DimasNeural',
    name: 'Dimas',
    lang: 'Javanese',
    from: 'ID',
    gender: 'Male',
  },
  {
    voice_id: 'jv-ID-SitiNeural',
    name: 'Siti',
    lang: 'Javanese',
    from: 'ID',
    gender: 'Female',
  },
  {
    voice_id: 'ka-GE-EkaNeural',
    name: 'Eka',
    lang: 'Georgian',
    from: 'GE',
    gender: 'Female',
  },
  {
    voice_id: 'ka-GE-GiorgiNeural',
    name: 'Giorgi',
    lang: 'Georgian',
    from: 'GE',
    gender: 'Male',
  },
  {
    voice_id: 'kk-KZ-AigulNeural',
    name: 'Aigul',
    lang: 'Kazakh',
    from: 'KZ',
    gender: 'Female',
  },
  {
    voice_id: 'kk-KZ-DauletNeural',
    name: 'Daulet',
    lang: 'Kazakh',
    from: 'KZ',
    gender: 'Male',
  },
  {
    voice_id: 'km-KH-PisethNeural',
    name: 'Piseth',
    lang: 'Khmer',
    from: 'KH',
    gender: 'Male',
  },
  {
    voice_id: 'km-KH-SreymomNeural',
    name: 'Sreymom',
    lang: 'Khmer',
    from: 'KH',
    gender: 'Female',
  },
  {
    voice_id: 'kn-IN-GaganNeural',
    name: 'Gagan',
    lang: 'Kannada',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'kn-IN-SapnaNeural',
    name: 'Sapna',
    lang: 'Kannada',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'ko-KR-InJoonNeural',
    name: 'InJoon',
    lang: 'Korean',
    from: 'KR',
    gender: 'Male',
  },
  {
    voice_id: 'ko-KR-SunHiNeural',
    name: 'SunHi',
    lang: 'Korean',
    from: 'KR',
    gender: 'Female',
  },
  {
    voice_id: 'lo-LA-ChanthavongNeural',
    name: 'Chanthavong',
    lang: 'Lao',
    from: 'LA',
    gender: 'Male',
  },
  {
    voice_id: 'lo-LA-KeomanyNeural',
    name: 'Keomany',
    lang: 'Lao',
    from: 'LA',
    gender: 'Female',
  },
  {
    voice_id: 'lt-LT-LeonasNeural',
    name: 'Leonas',
    lang: 'Lithuanian',
    from: 'LT',
    gender: 'Male',
  },
  {
    voice_id: 'lt-LT-OnaNeural',
    name: 'Ona',
    lang: 'Lithuanian',
    from: 'LT',
    gender: 'Female',
  },
  {
    voice_id: 'lv-LV-EveritaNeural',
    name: 'Everita',
    lang: 'Latvian',
    from: 'LV',
    gender: 'Female',
  },
  {
    voice_id: 'lv-LV-NilsNeural',
    name: 'Nils',
    lang: 'Latvian',
    from: 'LV',
    gender: 'Male',
  },
  {
    voice_id: 'mk-MK-AleksandarNeural',
    name: 'Aleksandar',
    lang: 'Macedonian',
    from: 'MK',
    gender: 'Male',
  },
  {
    voice_id: 'mk-MK-MarijaNeural',
    name: 'Marija',
    lang: 'Macedonian',
    from: 'MK',
    gender: 'Female',
  },
  {
    voice_id: 'ml-IN-MidhunNeural',
    name: 'Midhun',
    lang: 'Malayalam',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'ml-IN-SobhanaNeural',
    name: 'Sobhana',
    lang: 'Malayalam',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'mn-MN-BataaNeural',
    name: 'Bataa',
    lang: 'Mongolian',
    from: 'MN',
    gender: 'Male',
  },
  {
    voice_id: 'mn-MN-YesuiNeural',
    name: 'Yesui',
    lang: 'Mongolian',
    from: 'MN',
    gender: 'Female',
  },
  {
    voice_id: 'mr-IN-AarohiNeural',
    name: 'Aarohi',
    lang: 'Marathi',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'mr-IN-ManoharNeural',
    name: 'Manohar',
    lang: 'Marathi',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'ms-MY-OsmanNeural',
    name: 'Osman',
    lang: 'Malay',
    from: 'MY',
    gender: 'Male',
  },
  {
    voice_id: 'ms-MY-YasminNeural',
    name: 'Yasmin',
    lang: 'Malay',
    from: 'MY',
    gender: 'Female',
  },
  {
    voice_id: 'mt-MT-GraceNeural',
    name: 'Grace',
    lang: 'Maltese',
    from: 'MT',
    gender: 'Female',
  },
  {
    voice_id: 'mt-MT-JosephNeural',
    name: 'Joseph',
    lang: 'Maltese',
    from: 'MT',
    gender: 'Male',
  },
  {
    voice_id: 'my-MM-NilarNeural',
    name: 'Nilar',
    lang: 'Burmese',
    from: 'MM',
    gender: 'Female',
  },
  {
    voice_id: 'my-MM-ThihaNeural',
    name: 'Thiha',
    lang: 'Burmese',
    from: 'MM',
    gender: 'Male',
  },
  {
    voice_id: 'nb-NO-FinnNeural',
    name: 'Finn',
    lang: 'Norwegian Bokmål',
    from: 'NO',
    gender: 'Male',
  },
  {
    voice_id: 'nb-NO-PernilleNeural',
    name: 'Pernille',
    lang: 'Norwegian Bokmål',
    from: 'NO',
    gender: 'Female',
  },
  {
    voice_id: 'ne-NP-HemkalaNeural',
    name: 'Hemkala',
    lang: 'Nepali',
    from: 'NP',
    gender: 'Female',
  },
  {
    voice_id: 'ne-NP-SagarNeural',
    name: 'Sagar',
    lang: 'Nepali',
    from: 'NP',
    gender: 'Male',
  },
  {
    voice_id: 'nl-BE-ArnaudNeural',
    name: 'Arnaud',
    lang: 'Dutch',
    from: 'BE',
    gender: 'Male',
  },
  {
    voice_id: 'nl-BE-DenaNeural',
    name: 'Dena',
    lang: 'Dutch',
    from: 'BE',
    gender: 'Female',
  },
  {
    voice_id: 'nl-NL-ColetteNeural',
    name: 'Colette',
    lang: 'Dutch',
    from: 'NL',
    gender: 'Female',
  },
  {
    voice_id: 'nl-NL-FennaNeural',
    name: 'Fenna',
    lang: 'Dutch',
    from: 'NL',
    gender: 'Female',
  },
  {
    voice_id: 'nl-NL-MaartenNeural',
    name: 'Maarten',
    lang: 'Dutch',
    from: 'NL',
    gender: 'Male',
  },
  {
    voice_id: 'pl-PL-MarekNeural',
    name: 'Marek',
    lang: 'Polish',
    from: 'PL',
    gender: 'Male',
  },
  {
    voice_id: 'pl-PL-ZofiaNeural',
    name: 'Zofia',
    lang: 'Polish',
    from: 'PL',
    gender: 'Female',
  },
  {
    voice_id: 'ps-AF-GulNawazNeural',
    name: 'GulNawaz',
    lang: 'Pashto',
    from: 'AF',
    gender: 'Male',
  },
  {
    voice_id: 'ps-AF-LatifaNeural',
    name: 'Latifa',
    lang: 'Pashto',
    from: 'AF',
    gender: 'Female',
  },
  {
    voice_id: 'pt-BR-AntonioNeural',
    name: 'Antonio',
    lang: 'Portuguese',
    from: 'BR',
    gender: 'Male',
  },
  {
    voice_id: 'pt-BR-FranciscaNeural',
    name: 'Francisca',
    lang: 'Portuguese',
    from: 'BR',
    gender: 'Female',
  },
  {
    voice_id: 'pt-PT-DuarteNeural',
    name: 'Duarte',
    lang: 'Portuguese',
    from: 'PT',
    gender: 'Male',
  },
  {
    voice_id: 'pt-PT-RaquelNeural',
    name: 'Raquel',
    lang: 'Portuguese',
    from: 'PT',
    gender: 'Female',
  },
  {
    voice_id: 'ro-RO-AlinaNeural',
    name: 'Alina',
    lang: 'Romanian',
    from: 'RO',
    gender: 'Female',
  },
  {
    voice_id: 'ro-RO-EmilNeural',
    name: 'Emil',
    lang: 'Romanian',
    from: 'RO',
    gender: 'Male',
  },
  {
    voice_id: 'ru-RU-DmitryNeural',
    name: 'Dmitry',
    lang: 'Russian',
    from: 'RU',
    gender: 'Male',
  },
  {
    voice_id: 'ru-RU-SvetlanaNeural',
    name: 'Svetlana',
    lang: 'Russian',
    from: 'RU',
    gender: 'Female',
  },
  {
    voice_id: 'si-LK-SameeraNeural',
    name: 'Sameera',
    lang: 'Sinhala',
    from: 'LK',
    gender: 'Male',
  },
  {
    voice_id: 'si-LK-ThiliniNeural',
    name: 'Thilini',
    lang: 'Sinhala',
    from: 'LK',
    gender: 'Female',
  },
  {
    voice_id: 'sk-SK-LukasNeural',
    name: 'Lukas',
    lang: 'Slovak',
    from: 'SK',
    gender: 'Male',
  },
  {
    voice_id: 'sk-SK-ViktoriaNeural',
    name: 'Viktoria',
    lang: 'Slovak',
    from: 'SK',
    gender: 'Female',
  },
  {
    voice_id: 'sl-SI-PetraNeural',
    name: 'Petra',
    lang: 'Slovenian',
    from: 'SI',
    gender: 'Female',
  },
  {
    voice_id: 'sl-SI-RokNeural',
    name: 'Rok',
    lang: 'Slovenian',
    from: 'SI',
    gender: 'Male',
  },
  {
    voice_id: 'so-SO-MuuseNeural',
    name: 'Muuse',
    lang: 'Somali',
    from: 'SO',
    gender: 'Male',
  },
  {
    voice_id: 'so-SO-UbaxNeural',
    name: 'Ubax',
    lang: 'Somali',
    from: 'SO',
    gender: 'Female',
  },
  {
    voice_id: 'sq-AL-AnilaNeural',
    name: 'Anila',
    lang: 'Albanian',
    from: 'AL',
    gender: 'Female',
  },
  {
    voice_id: 'sq-AL-IlirNeural',
    name: 'Ilir',
    lang: 'Albanian',
    from: 'AL',
    gender: 'Male',
  },
  {
    voice_id: 'sr-RS-NicholasNeural',
    name: 'Nicholas',
    lang: 'Serbian',
    from: 'RS',
    gender: 'Male',
  },
  {
    voice_id: 'sr-RS-SophieNeural',
    name: 'Sophie',
    lang: 'Serbian',
    from: 'RS',
    gender: 'Female',
  },
  {
    voice_id: 'su-ID-JajangNeural',
    name: 'Jajang',
    lang: 'Sundanese',
    from: 'ID',
    gender: 'Male',
  },
  {
    voice_id: 'su-ID-TutiNeural',
    name: 'Tuti',
    lang: 'Sundanese',
    from: 'ID',
    gender: 'Female',
  },
  {
    voice_id: 'sv-SE-MattiasNeural',
    name: 'Mattias',
    lang: 'Swedish',
    from: 'SE',
    gender: 'Male',
  },
  {
    voice_id: 'sv-SE-SofieNeural',
    name: 'Sofie',
    lang: 'Swedish',
    from: 'SE',
    gender: 'Female',
  },
  {
    voice_id: 'sw-KE-RafikiNeural',
    name: 'Rafiki',
    lang: 'Swahili',
    from: 'KE',
    gender: 'Male',
  },
  {
    voice_id: 'sw-KE-ZuriNeural',
    name: 'Zuri',
    lang: 'Swahili',
    from: 'KE',
    gender: 'Female',
  },
  {
    voice_id: 'sw-TZ-DaudiNeural',
    name: 'Daudi',
    lang: 'Swahili',
    from: 'TZ',
    gender: 'Male',
  },
  {
    voice_id: 'sw-TZ-RehemaNeural',
    name: 'Rehema',
    lang: 'Swahili',
    from: 'TZ',
    gender: 'Female',
  },
  {
    voice_id: 'ta-IN-PallaviNeural',
    name: 'Pallavi',
    lang: 'Tamil',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'ta-IN-ValluvarNeural',
    name: 'Valluvar',
    lang: 'Tamil',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'ta-LK-KumarNeural',
    name: 'Kumar',
    lang: 'Tamil',
    from: 'LK',
    gender: 'Male',
  },
  {
    voice_id: 'ta-LK-SaranyaNeural',
    name: 'Saranya',
    lang: 'Tamil',
    from: 'LK',
    gender: 'Female',
  },
  {
    voice_id: 'ta-MY-KaniNeural',
    name: 'Kani',
    lang: 'Tamil',
    from: 'MY',
    gender: 'Female',
  },
  {
    voice_id: 'ta-MY-SuryaNeural',
    name: 'Surya',
    lang: 'Tamil',
    from: 'MY',
    gender: 'Male',
  },
  {
    voice_id: 'ta-SG-AnbuNeural',
    name: 'Anbu',
    lang: 'Tamil',
    from: 'SG',
    gender: 'Male',
  },
  {
    voice_id: 'ta-SG-VenbaNeural',
    name: 'Venba',
    lang: 'Tamil',
    from: 'SG',
    gender: 'Female',
  },
  {
    voice_id: 'te-IN-MohanNeural',
    name: 'Mohan',
    lang: 'Telugu',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'te-IN-ShrutiNeural',
    name: 'Shruti',
    lang: 'Telugu',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'th-TH-NiwatNeural',
    name: 'Niwat',
    lang: 'Thai',
    from: 'TH',
    gender: 'Male',
  },
  {
    voice_id: 'th-TH-PremwadeeNeural',
    name: 'Premwadee',
    lang: 'Thai',
    from: 'TH',
    gender: 'Female',
  },
  {
    voice_id: 'tr-TR-AhmetNeural',
    name: 'Ahmet',
    lang: 'Turkish',
    from: 'TR',
    gender: 'Male',
  },
  {
    voice_id: 'tr-TR-EmelNeural',
    name: 'Emel',
    lang: 'Turkish',
    from: 'TR',
    gender: 'Female',
  },
  {
    voice_id: 'uk-UA-OstapNeural',
    name: 'Ostap',
    lang: 'Ukrainian',
    from: 'UA',
    gender: 'Male',
  },
  {
    voice_id: 'uk-UA-PolinaNeural',
    name: 'Polina',
    lang: 'Ukrainian',
    from: 'UA',
    gender: 'Female',
  },
  {
    voice_id: 'ur-IN-GulNeural',
    name: 'Gul',
    lang: 'Urdu',
    from: 'IN',
    gender: 'Female',
  },
  {
    voice_id: 'ur-IN-SalmanNeural',
    name: 'Salman',
    lang: 'Urdu',
    from: 'IN',
    gender: 'Male',
  },
  {
    voice_id: 'ur-PK-AsadNeural',
    name: 'Asad',
    lang: 'Urdu',
    from: 'PK',
    gender: 'Male',
  },
  {
    voice_id: 'ur-PK-UzmaNeural',
    name: 'Uzma',
    lang: 'Urdu',
    from: 'PK',
    gender: 'Female',
  },
  {
    voice_id: 'uz-UZ-MadinaNeural',
    name: 'Madina',
    lang: 'Uzbek',
    from: 'UZ',
    gender: 'Female',
  },
  {
    voice_id: 'uz-UZ-SardorNeural',
    name: 'Sardor',
    lang: 'Uzbek',
    from: 'UZ',
    gender: 'Male',
  },
  {
    voice_id: 'vi-VN-HoaiMyNeural',
    name: 'HoaiMy',
    lang: 'Vietnamese',
    from: 'VN',
    gender: 'Female',
  },
  {
    voice_id: 'vi-VN-NamMinhNeural',
    name: 'NamMinh',
    lang: 'Vietnamese',
    from: 'VN',
    gender: 'Male',
  },
  {
    voice_id: 'zh-CN-XiaoxiaoNeural',
    name: 'Xiaoxiao',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Female',
  },
  {
    voice_id: 'zh-CN-XiaoyiNeural',
    name: 'Xiaoyi',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Female',
  },
  {
    voice_id: 'zh-CN-YunjianNeural',
    name: 'Yunjian',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Male',
  },
  {
    voice_id: 'zh-CN-YunxiNeural',
    name: 'Yunxi',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Male',
  },
  {
    voice_id: 'zh-CN-YunxiaNeural',
    name: 'Yunxia',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Male',
  },
  {
    voice_id: 'zh-CN-YunyangNeural',
    name: 'Yunyang',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Male',
  },
  {
    voice_id: 'zh-CN-liaoning-XiaobeiNeural',
    name: 'liaoning-Xiaobei',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Female',
  },
  {
    voice_id: 'zh-CN-shaanxi-XiaoniNeural',
    name: 'shaanxi-Xiaoni',
    lang: 'Chinese',
    from: 'CN',
    gender: 'Female',
  },
  {
    voice_id: 'zh-HK-HiuGaaiNeural',
    name: 'HiuGaai',
    lang: 'Chinese',
    from: 'HK',
    gender: 'Female',
  },
  {
    voice_id: 'zh-HK-HiuMaanNeural',
    name: 'HiuMaan',
    lang: 'Chinese',
    from: 'HK',
    gender: 'Female',
  },
  {
    voice_id: 'zh-HK-WanLungNeural',
    name: 'WanLung',
    lang: 'Chinese',
    from: 'HK',
    gender: 'Male',
  },
  {
    voice_id: 'zh-TW-HsiaoChenNeural',
    name: 'HsiaoChen',
    lang: 'Chinese',
    from: 'TW',
    gender: 'Female',
  },
  {
    voice_id: 'zh-TW-HsiaoYuNeural',
    name: 'HsiaoYu',
    lang: 'Chinese',
    from: 'TW',
    gender: 'Female',
  },
  {
    voice_id: 'zh-TW-YunJheNeural',
    name: 'YunJhe',
    lang: 'Chinese',
    from: 'TW',
    gender: 'Male',
  },
  {
    voice_id: 'zu-ZA-ThandoNeural',
    name: 'Thando',
    lang: 'Zulu',
    from: 'ZA',
    gender: 'Female',
  },
  {
    voice_id: 'zu-ZA-ThembaNeural',
    name: 'Themba',
    lang: 'Zulu',
    from: 'ZA',
    gender: 'Male',
  },
];

export { edgeTTSVoiceIds };
