name: Push Kubernetes Backend Prod Deployment

on:
  workflow_dispatch:

env:
  IMAGE_NAME: docker.io/shaunly/real_char
  K8S_DEPLOYMENT_NAME: realchar-deployment

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker push
      run: |
        docker pull ${{ env.IMAGE_NAME }}:latest
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:prod
        docker push ${{ env.IMAGE_NAME }}:prod

  k8s-deployment:
    needs: [docker-push]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      id: install

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ./kubeconfig.yaml
        export KUBECONFIG=./kubeconfig.yaml
        kubectl rollout restart deployment ${{ env.K8S_DEPLOYMENT_NAME }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#335c05'
        SLACK_MESSAGE: new version has started to update for realchar backend (api server) in prod env
        SLACK_TITLE: prod realchar backend (api server) update
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
