name: Push Kubernetes Backend Prod Deployment

on:
  workflow_dispatch:

env:
  IMAGE_NAME: docker.io/shaunly/real_char
  K8S_DEPLOYMENT_NAME: realchar-deployment

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker push
      run: |
        docker pull ${{ env.IMAGE_NAME }}:latest
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:prod
        docker push ${{ env.IMAGE_NAME }}:prod

  k8s-deployment:
    needs: [docker-push]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_ASSISTLY}}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'rc-prod'
        location: 'us-central1'

    - name: Deploy to Kubernetes
      run: kubectl rollout restart deployment deployment-rc-api

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#335c05'
        SLACK_MESSAGE: api.realchar.ai -- ${{ github.event.head_commit.message }}
        SLACK_TITLE: backend (api server) update
        SLACK_FOOTER: api.realchar.ai
        MSG_MINIMAL: true
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
