name: Push Kubernetes Frontend Prod Deployment

on:
  workflow_dispatch:

env:
  IMAGE_NAME: docker.io/shaunly/real_char_frontend_next
  K8S_DEPLOYMENT_NAME: react-deployment

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./client/next-web
          file: ./client/next-web/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:prod
          build-args: |
            REACT_APP_BUILD_NUMBER=${{ github.ref }}
            NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAVqhwbdB8I56HAMVVlgJKZcfrBkKI2AhQ
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=assistly-kubernetes.firebaseapp.com
            NEXT_PUBLIC_FIREBASE_PROJECT_ID=assistly-kubernetes
            NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=assistly-kubernetes.appspot.com
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=806733379891
            NEXT_PUBLIC_FIREBASE_APP_ID=1:806733379891:web:48bf124c0d9b90298e6646
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XVWF8XDKS5
            API_HOST=https://api.realchar.ai
            NEXT_PUBLIC_API_HOST=https://api.realchar.ai
            NEXT_PUBLIC_TURN_SERVER_API_ENDPOINT=https://testrtcturn.metered.live/api/v1/turn/credentials?apiKey=1061f118b12c30023acb17aafcf8c224c8f1
 
  k8s-deployment:
    needs: [docker-push]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_ASSISTLY}}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'cluster-1'
        location: 'us-central1-c'

    - name: Deploy to Kubernetes
      run: kubectl rollout restart deployment ${{ env.K8S_DEPLOYMENT_NAME }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#335c05'
        SLACK_MESSAGE: new version has started to update for realchar frontend in prod env
        SLACK_TITLE: prod realchar frontend update
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
