name: Build Push and Deploy Docker Image for Frontend (NextJS)

on:
  release:
    types: [published]  # This triggers the workflow when a release is published

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./client/next-web
        file: ./client/next-web/Dockerfile
        push: true
        tags: shaunly/real_char_frontend_next:latest
        build-args: |
          REACT_APP_BUILD_NUMBER=${{ github.ref }}
          NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAVqhwbdB8I56HAMVVlgJKZcfrBkKI2AhQ
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=assistly-kubernetes.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=assistly-kubernetes
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=assistly-kubernetes.appspot.com
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=806733379891
          NEXT_PUBLIC_FIREBASE_APP_ID=1:806733379891:web:48bf124c0d9b90298e6646
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XVWF8XDKS5
          API_HOST=https://api.dev.realchar.ai

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ./kubeconfig.yaml
        export KUBECONFIG=./kubeconfig.yaml
        kubectl rollout restart deployment react-next-deployment
